[options]
data_dir = /var/lib/odoo
addons_path = /workspace/custom-addons,/workspace/custom-addons/proyecto-libreria,/workspace/odoo.18.0/addons
admin_passwd = $pbkdf2-sha512$600000$phSCMKZ07l3rXat1LsX4vw$TpelAZqsaZTeldV2fjiofD8Uf9VKMWfV1Sorzo0pHblnSos/6wvJWrEzHQ7Bi6Q9rBTLj9zUhGi1NrF8pbwbOQ
db_host = pgdb
db_user = odoo
db_password = odoo
list_db = True
http_enable = True
http_interface = 
http_port = 8069
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 0
limit_time_real_cron = -1
max_cron_threads = 2
workers = 0

